import { test, expect } from '@playwright/test';

test('AI override streams to dashboard; next sample preserves the historical disagreement', async ({ page, request }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const coach = page.getByTestId('coach-coach-01');
  await expect(coach.getByTestId('verification')).toContainText('AI disagreement recorded', { timeout: 10000 });
  await expect(coach.getByTestId('occupancy')).toHaveText('90%');
  await expect(coach).toHaveAttribute('data-status', 'red');
  await expect(coach).toContainText('Regular: 0 · AI: 9');
  await expect(coach).toContainText('AI count used for this observation');
  await page.screenshot({ path: 'test-results/verification-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/verification-mobile.png', fullPage: true });
  await expect(coach).toContainText('Historical check; newer reading shown', { timeout: 10000 });
  await expect(coach.getByTestId('occupancy')).toHaveText('0%');
  await expect(coach).toHaveAttribute('data-status', 'green');
  const history = await (await request.get('/api/observations')).json();
  const checked = history.find((row: { verification: { status: string } }) => row.verification.status === 'verified');
  expect(checked.regular_passenger_count).toBe(0);
  expect(checked.passenger_count).toBe(9);
  expect(checked.verification.disagreement).toBe(true);
  const saved = page.getByTestId(`history-${checked.id}`);
  await expect(saved).toContainText('Disagreement · AI used');
  await expect(saved).toContainText('90% · Red');
  await expect(saved.locator('td').nth(2)).toHaveText('0');
  await expect(saved.locator('td').nth(3)).toHaveText('9');
  await expect(saved.locator('time').nth(0)).toHaveAttribute('datetime', checked.observed_at);
  await expect(saved.locator('time').nth(1)).toHaveAttribute('datetime', checked.verification.completed_at);
  await page.screenshot({ path: 'test-results/history-mobile.png', fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByLabel('Coach', { exact: true }).selectOption('coach-03');
  await expect(page.getByText('No observations saved for this selection.')).toBeVisible();
  await page.getByLabel('Coach', { exact: true }).selectOption('coach-01');
  await expect(saved).toBeVisible();
  await page.route('**/api/history?*', route => route.abort());
  await expect(page.getByRole('alert')).toContainText('Showing the last loaded records', { timeout: 8000 });
  await page.unroute('**/api/history?*');
  await page.getByRole('button', { name: 'Refresh history' }).click();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await expect(saved).toBeVisible();
  expect(errors).toEqual([]);
});
